version: "3.7"
services:
  app:
    build:
      args:
        user: hakaton
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: smevapp
    container_name: app
    restart: unless-stopped
    working_dir: /var/www/
    environment:
      - DB_HOST=postgres
    volumes:
      - ./:/var/www
    networks:
      - hakaton
    links:
      - postgres

  nginx:
    image: nginx:alpine
    container_name: nginx1
    restart: unless-stopped
    ports:
      - ${APP_PORT}:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx/app_conf.local:/etc/nginx/conf.d/default.conf
    networks:
      - hakaton

  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: hakaton
    ports:
      - ${POSTGRESS_PORT}:5432
    networks:
      - hakaton
    restart: unless-stopped

  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - ${ADMINER_PORT}:8080
    links:
      - postgres
    networks:
      - hakaton

networks:
  hakaton:
    driver: bridge
